# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('ships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='departments.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='ship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ships.Ship'),
        ),
    ]
