# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170420_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_SAP',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
