# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Images',
                'verbose_name': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('iss_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('submitted', 'Submitted')], default='pending', max_length=50)),
                ('deck_no', models.CharField(max_length=100)),
                ('compartment', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Issues',
                'verbose_name': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('sol_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solution_text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updataed_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Solutions',
                'verbose_name': 'Solutions',
            },
        ),
    ]
