# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('ships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='parent_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='image',
            name='parent_solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues.Solution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='departments.Department'),
        ),
        migrations.AddField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ships.Ship'),
        ),
        migrations.AddField(
            model_name='solution',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
