# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20170409_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='updataed_time',
            new_name='updated_time',
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='solution',
            name='parent_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='issues.Issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
