# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20170417_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Issues', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solutions', 'verbose_name_plural': 'Solutions'},
        ),
    ]
