# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='departments',
            field=models.ManyToManyField(related_name='ships', to='departments.Department'),
        ),
    ]
