# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ships', '0002_ship_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Ships', 'verbose_name_plural': 'Ships'},
        ),
        migrations.AddField(
            model_name='ship',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ship', to=settings.AUTH_USER_MODEL),
        ),
    ]
