# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Departments',
                'verbose_name': 'Departments',
            },
        ),
    ]
